ALTER TABLE tasks ADD COLUMN reframe_layout TEXT NOT NULL DEFAULT 'single';
ALTER TABLE tasks ADD COLUMN speaker_active_switch INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN split_divider INTEGER NOT NULL DEFAULT 0;
